### ISSUE TITLE
Mensastaat inzien als pdf

### ISSUE THREAD

**Issue by Kipjr** [VSLCatena/mensa#20]
Koker kan niet zien wat zijn/haar consumpties zijn als er geen printer is....

**Comment by SubSide** [comment]
Dit kan al via mensa

**Comment by Kipjr** [comment]
Ook al is de mensa nog niet gesloten?

**Comment by SubSide** [comment]
Yes, dit kan altijd. Je krijgt dan de pure html te zien wat ook naar de printer wordt verstuurd.
