### ISSUE TITLE
Workflow is scoped to an arbitrary branch

### ISSUE THREAD

**Issue by SubSide** [VSLCatena/mensa#50]
It looks like the workflow files are scoped to an arbitrary branch. e.g. `corona` and `feature/docker`.
Should be scoped to `main`, and/or `develop`.

**Comment by Kipjr** [comment]
workflow docker-publish only executes when version is published

workflow Laravel will be fixed

**Comment by Kipjr** [comment]
#51

**Comment by SubSide** [comment]
Hmm, you sure about docker-publish? It is talking about `master` but it has `feature/docker` as branch

```on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - feature/docker```

**Comment by Kipjr** [comment]
typo I guess
